spring.application.name=auth-service

server.port=7072

spring.datasource.url=jdbc:mysql://localhost:3306/db_auth?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret=mi_clave_super_secreta_para_jwt_2026_123456789