# =============================================
# AUTH SERVICE — Configuración común
# Para ejecutar localmente: -Dspring.profiles.active=local
# Para Docker: SPRING_PROFILES_ACTIVE=docker (docker-compose lo setea)
# =============================================

spring.application.name=auth-service
spring.profiles.default=local

server.port=7072

# JPA — configuración común (sin URL de BD)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JWT
jwt.secret=mi_clave_super_secreta_para_jwt_2026_123456789