# =============================================
# HISTORY SERVICE — Perfil LOCAL (Windows)
# Activo con: -Dspring.profiles.active=local
# =============================================

spring.datasource.url=jdbc:mysql://localhost:3306/db_history?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
